In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import Markdown, display, HTML

# Fix the dying kernel problem (only a problem in some installations - you can remove it, if it works without it)
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'

# Numpy tasks

For a detailed reference check out: https://numpy.org/doc/stable/reference/arrays.indexing.html.

**Task 1.** Calculate the sigmoid (logistic) function on every element of the following numpy array [0.3, 1.2, -1.4, 0.2, -0.1, 0.1, 0.8, -0.25] and print the last 5 elements. Use only vector operations.

In [9]:
array=1/(1 + np.exp(-np.array([0.3, 1.2, -1.4, 0.2, -0.1, 0.1, 0.8, -0.25])))
print(array[-5:])

[0.549834   0.47502081 0.52497919 0.68997448 0.4378235 ]


**Task 2.** Calculate the dot product of the following two vectors:<br/>
$x = [3, 1, 4, 2, 6, 1, 4, 8]$<br/>
$y = [5, 2, 3, 12, 2, 4, 17, 11]$<br/>
a) by using element-wise mutliplication and np.sum,<br/>
b) by using np.dot,<br/>
b) by using np.matmul and transposition (y.reshape(-1, 1), the alternative y.T will not work because T does not work on 1D arrays).

In [26]:
𝑥=np.array([3,1,4,2,6,1,4,8])
𝑦=np.array([5,2,3,12,2,4,17,11])
print(np.sum(x*y))
print(np.dot(x,y))
print(np.sum(np.diagonal(np.matmul(x.reshape(-1,1),np.transpose(y.reshape(-1,1))))))

225
225
225


**Task 3.** Calculate value of the logistic model<br/>
$$y = \frac{1}{1 + e^{-x_0 \theta_0 - \ldots - x_9 \theta_9 - \theta_{10}}}$$
for<br/>
$x = [1.2, 2.3, 3.4, -0.7, 4.2, 2.7, -0.5, 1.4, -3.3, 0.2]$<br/>
$\theta = [2.7, 0.33, -2.12, -1.73, 2.9, -5.8, -0.9, 12.11, 3.43, -0.5, -1.65]$<br/>
and print the result. Use only vector operations.

In [3]:
x=np.array([1.2,2.3,3.4,-0.7,4.2,2.7,-0.5,1.4,-3.3,0.2])
𝜃=np.array([2.7,0.33,-2.12,-1.73,2.9,-5.8,-0.9,12.11,3.43,-0.5,-1.65])
power=np.sum([(-1)*x[i]*𝜃[i] for i in range(len(x))])-𝜃[10]
e_power=np.exp(power)
y=1.0/(1.0+e_power)
print(round(y,8))

0.24176998


**Task 4.** Calculate value of the multivariate linear regression model<br/>
$$y = A x + B$$
for<br/>
$A = \begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \end{bmatrix}$<br/>
$B = \begin{bmatrix} 0.2 \\ 0.3 \end{bmatrix}$<br/>
$x = [1, 2, 3]^T$<br/>
and print the result. Use only vector and matrix operations.

In [81]:
a=np.array([[1,2,1],[3,0,1]])
b=np.array([0.2,0.3])
x=np.array([1,2,3])
print((np.matmul(a,x)+b).reshape(-1,1))

[[8.2]
 [6.3]]


# Pandas

## Load datasets

- Steam (https://www.kaggle.com/tamber/steam-video-games)

- MovieLens (https://grouplens.org/datasets/movielens/)

In [116]:
steam_df = pd.read_csv(os.path.join("data", "steam", "steam-200k.csv"), 
                       names=['user-id', 'game-title', 'behavior-name', 'value', 'zero'])

ml_ratings_df = pd.read_csv(os.path.join("data", "movielens_small", "ratings.csv"))
ml_movies_df = pd.read_csv(os.path.join("data", "movielens_small", "movies.csv"))

## Merge both MovieLens DataFrames into one

In [117]:
ml_df = pd.merge(ml_ratings_df, ml_movies_df, on='movieId')
ml_df.head(10)

userId  movieId  rating   timestamp             title  \
0       1        1     4.0   964982703  Toy Story (1995)   
1       5        1     4.0   847434962  Toy Story (1995)   
2       7        1     4.5  1106635946  Toy Story (1995)   
3      15        1     2.5  1510577970  Toy Story (1995)   
4      17        1     4.5  1305696483  Toy Story (1995)   
5      18        1     3.5  1455209816  Toy Story (1995)   
6      19        1     4.0   965705637  Toy Story (1995)   
7      21        1     3.5  1407618878  Toy Story (1995)   
8      27        1     3.0   962685262  Toy Story (1995)   
9      31        1     5.0   850466616  Toy Story (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1  Adventure|Animation|Children|Comedy|Fantasy  
2  Adventure|Animation|Children|Comedy|Fantasy  
3  Adventure|Animation|Children|Comedy|Fantasy  
4  Adventure|Animation|Children|Comedy|Fantasy  
5  Adventure|Animation|Children|Comedy|Fantasy  
6  Adventure|Animation|Children|Comedy|Fantasy  
7  Adventure|Animation|Children|Comedy|Fantasy  
8  Adventure|Animation|Children|Comedy|Fantasy  
9  Adventure|Animation|Children|Comedy|Fantasy

## Pandas tasks - Steam dataset

**Task 5.** How many people made a purchase in the Steam dataset? Remember that a person could buy many games, but you need to count every person once.

In [23]:
steam_df.head()

user-id                  game-title behavior-name  value  zero
0  151603712  The Elder Scrolls V Skyrim      purchase    1.0     0
1  151603712  The Elder Scrolls V Skyrim          play  273.0     0
2  151603712                   Fallout 4      purchase    1.0     0
3  151603712                   Fallout 4          play   87.0     0
4  151603712                       Spore      purchase    1.0     0

**Task 6.** How many people made a purchase of "The Elder Scrolls V Skyrim"?

In [41]:
# gamers_grouped=steam_df.groupby("game-title").count().reset_index()
# gamers_grouped.head()
# tes5_fans=gamers_grouped.loc[gamers_grouped["game-title"]=="The Elder Scrolls V Skyrim"]
# print(tes5_fans["user-id"])
# steam_df.loc[steam_df["game-title"]=="The Elder Scrolls V Skyrim",["user-id"]].head()
print(len(pd.unique(steam_df.loc[steam_df["game-title"]=="The Elder Scrolls V Skyrim",["user-id"]]["user-id"])))

717


**Task 7.** How many purchases people made on average?

In [63]:
purchases=steam_df.loc[steam_df["behavior-name"]=="purchase",["user-id"]].reset_index()
grouped=purchases.groupby("user-id").count()
print(round(np.mean(grouped["index"]),2))

10.45


**Task 8.** Who bought the most games?

In [93]:
import numpy as np
purchases=steam_df.loc[steam_df["behavior-name"]=="purchase",["user-id"]].reset_index()
grouped=purchases.groupby("user-id").count().reset_index()
max_purchases=np.max(grouped["index"])
max_player=grouped.loc[grouped["index"]==max_purchases,["user-id","index"]]
print(max_player.iloc[0]["user-id"])

62990992


**Task 9.** How many hours on average people played in "The Elder Scrolls V Skyrim"?

In [39]:
skyrim_plays=steam_df.loc[(steam_df["behavior-name"]=="play") & 
                          (steam_df["game-title"]=="The Elder Scrolls V Skyrim"),
                          ["user-id","value"]].reset_index()
grouped=skyrim_plays.groupby("user-id").sum().reset_index()
print(round(np.mean(grouped["value"]),2))

104.71


**Task 10.** Which games were played the most (in terms of the number of hours played)? Display a DataFrame with the first 10 titles and respective numbers of hours.

In [43]:
games_played=steam_df.loc[(steam_df["behavior-name"]=="play"),
                          ["game-title","value"]].reset_index()
games_played=games_played.groupby("game-title").sum()
games_played=games_played.sort_values(by='value', ascending=False).reset_index()
games_played[["game-title","value"]].head(10)
print(games_played[["game-title","value"]].head(10))

                                    game-title     value
0                                       Dota 2  981684.6
1              Counter-Strike Global Offensive  322771.6
2                              Team Fortress 2  173673.3
3                               Counter-Strike  134261.1
4                   Sid Meier's Civilization V   99821.3
5                        Counter-Strike Source   96075.5
6                   The Elder Scrolls V Skyrim   70889.3
7                                  Garry's Mod   49725.3
8  Call of Duty Modern Warfare 2 - Multiplayer   42009.9
9                                Left 4 Dead 2   33596.7


**Task 11.** Which games are the most consistently played (in terms of the average number of hours played)? Print a DataFrame with the first 10 titles and respective numbers of hours.

In [13]:
games_played=steam_df.loc[(steam_df["behavior-name"]=="play"),
                          ["game-title","value"]].reset_index()
games_played=games_played.groupby("game-title").mean()
games_played=games_played.sort_values(by='value', ascending=False).reset_index()
print(games_played[["game-title","value"]].head(10))

                          game-title        value
0            Eastside Hockey Manager  1295.000000
1  Baldur's Gate II Enhanced Edition   475.255556
2                    FIFA Manager 09   411.000000
3                          Perpetuum   400.975000
4              Football Manager 2014   391.984615
5              Football Manager 2012   390.453165
6              Football Manager 2010   375.048571
7              Football Manager 2011   365.703226
8                  Freaking Meatbags   331.000000
9        Out of the Park Baseball 16   330.400000


**Task 12\*\*.** Fix the above for the fact that 0 hours played is not listed, but only a purchase is recorded in such a case.

In [47]:
user_ids=steam_df["user-id"].unique().tolist()
game_titles=steam_df["game-title"].unique().tolist()
# behavior_names=steam_df["behavior-name"].unique().tolist()
# values=steam_df["value"].unique().tolist()
# zeros=steam_df["zero"].unique().tolist()
# games_new=pd.DataFrame(list(itertools.product(user_id,game_title,behavior_name,value,zero))).rename(columns={0:'user',1:'cat'})
# print(games_new)
games_fixed=steam_df.copy()
print(games_fixed.head(20))
# for user in user_ids:
#     for title in game_titles:
#         if ((games_fixed["user-id"]==user) & 
#             (games_fixed["game-title"]==title) & 
#             (games_fixed["behavior-name"]=="play")).any() == False:
#             games_fixed.append({"user-id":user,"game-title":title,"behavior-name":"play","value":0,"zero":0},ignore_index=True)
games_played=games_fixed.loc[(steam_df["behavior-name"]=="play"),
                          ["game-title","value"]].reset_index()
games_played=games_played.groupby("game-title").mean()
games_played=games_played.sort_values(by='value', ascending=False).reset_index()
print(games_played[["game-title","value"]].head(10))

      user-id                  game-title behavior-name  value  zero
0   151603712  The Elder Scrolls V Skyrim      purchase    1.0     0
1   151603712  The Elder Scrolls V Skyrim          play  273.0     0
2   151603712                   Fallout 4      purchase    1.0     0
3   151603712                   Fallout 4          play   87.0     0
4   151603712                       Spore      purchase    1.0     0
5   151603712                       Spore          play   14.9     0
6   151603712           Fallout New Vegas      purchase    1.0     0
7   151603712           Fallout New Vegas          play   12.1     0
8   151603712               Left 4 Dead 2      purchase    1.0     0
9   151603712               Left 4 Dead 2          play    8.9     0
10  151603712                    HuniePop      purchase    1.0     0
11  151603712                    HuniePop          play    8.5     0
12  151603712               Path of Exile      purchase    1.0     0
13  151603712               Path o

**Task 13.** Apply the sigmoid function
$$f(x) = \frac{1}{1 + e^{-\frac{1}{100}x}}$$
to hours played and print a DataFrame with the first 10 rows from the entire Steam dataset after this change.

In [50]:
steam=steam_df.copy()
steam.loc[steam["behavior-name"]=="play",["value"]]=steam["value"].apply(lambda x : 1/(1+np.exp(-0.01*x)))
print(steam.head(10))

     user-id                  game-title behavior-name     value  zero
0  151603712  The Elder Scrolls V Skyrim      purchase  1.000000     0
1  151603712  The Elder Scrolls V Skyrim          play  0.938774     0
2  151603712                   Fallout 4      purchase  1.000000     0
3  151603712                   Fallout 4          play  0.704746     0
4  151603712                       Spore      purchase  1.000000     0
5  151603712                       Spore          play  0.537181     0
6  151603712           Fallout New Vegas      purchase  1.000000     0
7  151603712           Fallout New Vegas          play  0.530213     0
8  151603712               Left 4 Dead 2      purchase  1.000000     0
9  151603712               Left 4 Dead 2          play  0.522235     0


## Pandas tasks - MovieLens dataset

**Task 14\*.** Calculate popularity (by the number of users who watched a movie) of all genres. Print a DataFrame with two columns: genre, n_users, where n_users contains the number of users who watched a given genre. Sort all genres in descending order.

In [127]:
import warnings
# warnings.filterwarnings("ignore", 'This pattern has match groups')

movies_grouped=ml_df.groupby("movieId").count()[["userId"]]
movies_grouped=movies_grouped.rename(columns={"userId":"n_users"})
movies_merged=pd.merge(movies_grouped,ml_df,on="movieId")[["movieId","n_users","genres"]].drop_duplicates()
movies_merged["genres"]=movies_merged["genres"].str.split("|")
genres_dict={}
for index,row in movies_merged.iterrows():
    for genre in row["genres"]:
        if genre not in genres_dict:
            genres_dict[genre]=0
        genres_dict[genre]+=row["n_users"]
genres_df=pd.DataFrame.from_dict(genres_dict,orient="index")
genres_df=genres_df.sort_values(by=0, ascending=False).reset_index()
genres_df.set_axis(["genre","n_users"], axis="columns", inplace=True)
print(genres_df)

                 genre  n_users
0                Drama    41928
1               Comedy    39053
2               Action    30635
3             Thriller    26452
4            Adventure    24161
5              Romance    18124
6               Sci-Fi    17243
7                Crime    16681
8              Fantasy    11834
9             Children     9208
10             Mystery     7674
11              Horror     7291
12           Animation     6988
13                 War     4859
14                IMAX     4145
15             Musical     4138
16             Western     1930
17         Documentary     1219
18           Film-Noir      870
19  (no genres listed)       47


**Task 15\*.** Calculate average rating for all genres. Print a DataFrame with two columns: genre, rating, where rating contains the average rating for a given genre. Sort all genres in descending order.

In [159]:
# movie_means=ml_df.groupby("movieId").mean()[["userId"]]
# movies=pd.merge(ml_df,movie_means,on="movieId").rename(columns={"userId_x":"userId","userId_y":"mean"})
# movies["genres"]=movies["genres"].str.split("|")
# ratings={}
# for index,row in movies.iterrows():
#     for genre in row["genres"]:
#         if genre not in ratings:
#             ratings[genre]=[]
#         ratings[genre].append(row["mean"])
# for genre,rating_list in rating_means.items():
#     ratings[genre]=np.mean(rating_list)
# ratings_df=pd.DataFrame.from_dict(ratings,orient="index")
# ratings_df=ratings_df.sort_values(by=0, ascending=False).reset_index()
# ratings_df.set_axis(["genre","rating"], axis="columns", inplace=True)
# print(ratings_df)

import numpy as np

movies=ml_df.copy()
movies["genres"]=movies["genres"].str.split("|")
ratings={}
genre_list=movies["genres"]
rating_list=movies["rating"]
for i in range(len(genre_list)):
    for genre in genre_list[i]:
        if genre not in ratings:
            ratings[genre]=[]
        ratings[genre].append(rating_list[i])
for genre,rating_list in ratings.items():
    ratings[genre]=np.mean(rating_list)
ratings_df=pd.DataFrame.from_dict(ratings,orient="index")
ratings_df=ratings_df.sort_values(by=0, ascending=False).reset_index()
ratings_df.set_axis(["genre","rating"], axis="columns", inplace=True)
print(ratings_df)

                 genre    rating
0            Film-Noir  3.920115
1                  War  3.808294
2          Documentary  3.797785
3                Crime  3.658294
4                Drama  3.656184
5              Mystery  3.632460
6            Animation  3.629937
7                 IMAX  3.618335
8              Western  3.583938
9              Musical  3.563678
10           Adventure  3.508609
11             Romance  3.506511
12            Thriller  3.493706
13             Fantasy  3.491001
14  (no genres listed)  3.489362
15              Sci-Fi  3.455721
16              Action  3.447984
17            Children  3.412956
18              Comedy  3.384721
19              Horror  3.258195


**Task 16.** Calculate each movie rating bias (deviation from the mean of all movies average rating). Print a DataFrame with the first 10 in the form: title, average rating, bias.

In [106]:
import numpy as np
movies=ml_movies_df.copy()
ratings=ml_ratings_df.copy()
mean_ratings=pd.merge(movies,ratings,on="movieId")[["title","rating"]].groupby("title").mean()
all_mean=np.mean(ratings["rating"])
bias_ratings=pd.merge(mean_ratings,movies,on="title")[["title","rating"]].rename(columns={"rating": "average_rating"})
bias_ratings["bias"]=(bias_ratings["average_rating"]-all_mean)
print(bias_ratings.head(10))

                                     title  average_rating      bias
0                               '71 (2014)        4.000000  0.498443
1  'Hellboy': The Seeds of Creation (2004)        4.000000  0.498443
2                   'Round Midnight (1986)        3.500000 -0.001557
3                      'Salem's Lot (2004)        5.000000  1.498443
4                'Til There Was You (1997)        4.000000  0.498443
5          'Tis the Season for Love (2015)        1.500000 -2.001557
6                       'burbs, The (1989)        3.176471 -0.325086
7                     'night Mother (1986)        3.000000 -0.501557
8              (500) Days of Summer (2009)        3.666667  0.165110
9           *batteries not included (1987)        3.285714 -0.215843
3.501556983616962


**Task 17.** Calculate each user rating bias (deviation from the mean of all users average rating). Print a DataFrame with the first 10 in the form: user_id, average rating, bias.

In [109]:
import numpy as np
movies=ml_movies_df.copy()
ratings=ml_ratings_df.copy()
mean_ratings=ratings[["userId","rating"]].groupby("userId").mean().reset_index()
all_mean=np.mean(ratings["rating"])
bias_ratings=mean_ratings[["userId","rating"]].rename(columns={"rating": "average_rating"})
bias_ratings["bias"]=(bias_ratings["average_rating"]-all_mean)
print(bias_ratings.head(10))

   userId  average_rating      bias
0       1        4.366379  0.864822
1       2        3.948276  0.446719
2       3        2.435897 -1.065660
3       4        3.555556  0.053999
4       5        3.636364  0.134807
5       6        3.493631 -0.007926
6       7        3.230263 -0.271294
7       8        3.574468  0.072911
8       9        3.260870 -0.240687
9      10        3.278571 -0.222986


**Task 18.** Randomly choose 10 movies and 10 users and print their interaction matrix in the form of a DataFrame with user_id as index and movie titles as columns. You can iterate over the DataFrame in this task. Alternatively, try using the DataFrame pivot and reindex methods and compare the execution time. Initialize the numpy random number generator with seed=4321.

In [233]:
user_ids = ml_df['userId'].unique()
movie_ids = ml_df['movieId'].unique()
rng = np.random.RandomState(seed=4321)
user_ids = sorted(list(rng.choice(user_ids, size=10)))
movie_ids = sorted(list(rng.choice(movie_ids, size=10)))
movie_titles=[ml_df[ml_df["movieId"]==x]["title"].iloc[0] for x in movie_ids]
df=pd.DataFrame(index=user_ids, columns=movie_titles)
for index, row in df.iterrows():
    for movie in df.columns:
        if ml_df[(ml_df["title"]==movie) & (ml_df["userId"]==index)].empty:
            df.loc[index][movie]="0.0"
        else:
            df.loc[index][movie]="1.0"
print(df)

    Father of the Bride (1950) Matrix, The (1999) Howards End (1992)  \
11                         1.0                1.0                1.0   
277                        1.0                1.0                1.0   
286                        1.0                0.0                1.0   
357                        1.0                1.0                1.0   
414                        1.0                0.0                1.0   
428                        1.0                0.0                1.0   
470                        1.0                1.0                1.0   
487                        1.0                0.0                1.0   
543                        1.0                0.0                1.0   
544                        1.0                1.0                1.0   

    Thirteen Conversations About One Thing (a.k.a. 13 Conversations) (2001)  \
11                                                 1.0                        
277                                              

## Pandas + numpy tasks

**Task 19.** Create the entire interaction matrix (2D numpy array) for the MovieLens dataset. Print the submatrix of the first 10 rows and 10 columns.

In [28]:
# user_ids = ml_df['userId'].unique()
# movie_ids = ml_df['movieId'].unique()
# movie_titles=[ml_df[ml_df["movieId"]==x]["title"].iloc[0] for x in movie_ids]
# arr=np.ndarray(shape=(len(user_ids),len(movie_ids)))
# for user in range(len(user_ids)):
#     for movie in range(len(movie_titles)):
#         if ml_df[(ml_df["title"]==movie_titles[movie]) & (ml_df["userId"]==user_ids[user])].empty:
#             arr[user][movie]="0.0"
#         else:
#             arr[user][movie]="1.0"
# print(arr[:10,:10])
array=np.zeros(shape=(10,10))
array[1:10,1:10]=ml_df.pivot_table(index='userId', columns='movieId', aggfunc=len, fill_value=0).values[0:9,0:9]
print(array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [6]:
# user_ids = ml_df['userId'].unique()
# users=len(user_ids)
# arr=np.zeros(shape=(users+1,users+1))
# for i in range(users):
#     i_movies=ml_df.loc[ml_df["userId"]==user_ids[i]]
#     for j in range(users):
#         j_movies=ml_df.loc[ml_df["userId"]==user_ids[j]]
#         i_j_movies=pd.merge(i_movies,j_movies,on="movieId")["movieId"]
#         arr[i+1][j+1]=len(i_j_movies)
        
# print(arr[:10,:10])

array=ml_df.pivot_table(index='userId', columns='movieId', aggfunc=len, fill_value=0).to_numpy(dtype=np.short)
print(array)

[[1 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 1 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]


**Task 21.** Calculate the matrix of size (n_items, n_items) where at position (i, j) there is the number of users who watched both movie i and movie j. Use a single matrix multiplication to obtain the result. To prevent memory error use only the first 1000 items. Print the submatrix of first 10 rows and 10 columns.

In [8]:
# movie_ids = ml_df['movieId'].unique()
# movies=len(movie_ids)
# arr=np.zeros(shape=(movies+1,movies+1))
# for i in range(movies):
#     i_users=ml_df.loc[ml_df["movieId"]==movie_ids[i]]
#     for j in range(movies):
#         j_users=ml_df.loc[ml_df["movieId"]==movie_ids[j]]
#         i_j_users=pd.merge(i_users,j_users,on="userId")["userId"]
#         arr[i+1][j+1]=len(i_j_users)
        
# print(arr[:10,:10])

array=ml_df.pivot_table(index='movieId', columns='userId', aggfunc=len, fill_value=0).to_numpy(dtype=np.short)[:1000,:1000]
print(array)

[[1 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]]
